# Generated by Django 3.2.24 on 2024-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='sex',
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
